name: "publish-image"
description: "Composite action to publish complyscribe images."

inputs:
  image:
    required: true
    description: The image repository location in the format of registry/name/app
  release_version:
    required: true
    description: The version to build type semver tags from
  no_cache:
    description: Skip using cache when building the image.
    required: false
    default: "false"
  skip_tests:
    description: Skip pre-push testing
    required: false
    default: "false"
outputs:
  image_sha:
    value: ${{ inputs.image }}@${{ steps.build-and-push.outputs.digest }}
    description: The published image with digest

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # pin@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # pin@v3

    # Tags are defined here based on workflow triggers
    - name: Define metadata
      id: meta
      uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # pin@v5
      with:
        images: ${{ inputs.image }}
        tags: |
          type=semver,pattern=v{{major}},enable=${{ !startsWith(inputs.release_version, 'v0.') }},value=${{ inputs.release_version }}
          type=semver,pattern=v{{major}}.{{minor}},value=${{ inputs.release_version }}
          type=semver,pattern=v{{version}},value=${{ inputs.release_version }}
          type=raw,value=${{ inputs.release_version }}-{{branch}}-{{sha}},enable=${{ github.event_name == 'workflow_dispatch' }}
          type=schedule,pattern={{date 'YYYYMMDD'}},prefix=${{ inputs.release_version }}.
        flavor: |
          latest=false

    - name: Build and export to Docker
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # pin@v5
      id: build-and-export
      with:
        context: "."
        load: true
        no-cache: ${{ inputs.no_cache == 'true' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Pre-push Image Scan
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # pin@0.33.1
      with:
        image-ref: ${{ inputs.image }}:${{ steps.meta.outputs.version }}
        exit-code: 1
        skip-files: "**/.venv/lib/**/METADATA"
        scanners: secret
        severity: HIGH,CRITICAL,MEDIUM

    - name: Pre-push testing
      if: ${{ inputs.skip_tests == 'false' }}
      uses: ./.github/actions/e2e-testing
      with:
        image: "docker-daemon:${{ inputs.image }}:${{ steps.meta.outputs.version }}"
        build: false

    # Does not rebuild. Uses internal cache from previous step.
    - name: Build and Push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # pin@v5
      id: build-and-push
      with:
        context: "."
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
